In [1]:
import pandas as pd
from tools.hand_parser import *
from random import choice
import warnings 
warnings.filterwarnings('ignore')

In [2]:
%%time
df = pd.read_csv("hand_combinations.csv", index_col=0).astype('int8')
df.rename(index=lambda i: i.replace("'", ""), inplace=True)
print(f"Memory usage: {round(sum(df.memory_usage(deep=True)) / 1024 / 1024, 1)}MB\n")
all_hands = list(df.index.values)
df

Memory usage: 433.2MB

CPU times: total: 19.8 s
Wall time: 19.9 s

,0,1,2,3,4,5,6,7,8,9,...,42,43,44,45,46,47,48,49,50,51
"(♠A, ♠2, ♠3, ♠4, ♠5)",0,1,1,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
"(♠A, ♠2, ♠3, ♠4, ♠6)",0,1,1,1,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
"(♠A, ♠2, ♠3, ♠4, ♠7)",0,1,1,1,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
"(♠A, ♠2, ♠3, ♠4, ♠8)",0,1,1,1,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
"(♠A, ♠2, ♠3, ♠4, ♠9)",0,1,1,1,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"(♦8, ♦9, ♦10, ♦J, ♦K)",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,0,1,1,0
"(♦8, ♦9, ♦10, ♦Q, ♦K)",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,1,1
"(♦8, ♦9, ♦J, ♦Q, ♦K)",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,0,1,1,1
"(♦8, ♦10, ♦J, ♦Q, ♦K)",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,1,1
"(♦9, ♦10, ♦J, ♦Q, ♦K)",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,1,1

In [3]:
%%time
df['ranking'] = df.index
df['ranking'] = df['ranking'].apply(lambda x: parse(str(x)[1:-1].split(", ")))
df

CPU times: total: 48.8 s
Wall time: 48.8 s

,0,1,2,3,4,5,6,7,8,9,...,43,44,45,46,47,48,49,50,51,ranking
"(♠A, ♠2, ♠3, ♠4, ♠5)",0,1,1,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,STRAIGHT FLUSH
"(♠A, ♠2, ♠3, ♠4, ♠6)",0,1,1,1,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,FLUSH
"(♠A, ♠2, ♠3, ♠4, ♠7)",0,1,1,1,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,FLUSH
"(♠A, ♠2, ♠3, ♠4, ♠8)",0,1,1,1,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,FLUSH
"(♠A, ♠2, ♠3, ♠4, ♠9)",0,1,1,1,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,FLUSH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"(♦8, ♦9, ♦10, ♦J, ♦K)",0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,1,1,0,FLUSH
"(♦8, ♦9, ♦10, ♦Q, ♦K)",0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,1,1,FLUSH
"(♦8, ♦9, ♦J, ♦Q, ♦K)",0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,1,1,1,FLUSH
"(♦8, ♦10, ♦J, ♦Q, ♦K)",0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,1,1,FLUSH
"(♦9, ♦10, ♦J, ♦Q, ♦K)",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,1,1,1,STRAIGHT FLUSH

In [4]:
# SHOWING RANDOM hand with its ranking

# for _ in range(10):
#     hand = choice(all_hands)
#     print(hand, df.at[hand, 'ranking'])

In [5]:
df['ranking'].value_counts()

???               1302540
PAIR              1098240
TWO PAIRS          123552
THREE               54912
STRAIGHT            10200
FLUSH                5108
FULL HOUSE           3744
FOUR                  624
STRAIGHT FLUSH         36
ROYAL FLUSH             4
Name: ranking, dtype: int64

# CLASSIFICATION

##### Create rank_dict for renaming columns for future purposes in classification

In [6]:
rankings = df['ranking'].value_counts().index.to_list()
# rankings.reverse()
# print(rankings)

rank_dict = {}
for i, el in enumerate(rankings):
    rank_dict[el] = i
rank_dict

{'???': 0,
 'PAIR': 1,
 'TWO PAIRS': 2,
 'THREE': 3,
 'STRAIGHT': 4,
 'FLUSH': 5,
 'FULL HOUSE': 6,
 'FOUR': 7,
 'STRAIGHT FLUSH': 8,
 'ROYAL FLUSH': 9}

In [7]:
df['labels'] = df['ranking'].replace(rank_dict)
df

,0,1,2,3,4,5,6,7,8,9,...,44,45,46,47,48,49,50,51,ranking,labels
"(♠A, ♠2, ♠3, ♠4, ♠5)",0,1,1,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,STRAIGHT FLUSH,8
"(♠A, ♠2, ♠3, ♠4, ♠6)",0,1,1,1,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,FLUSH,5
"(♠A, ♠2, ♠3, ♠4, ♠7)",0,1,1,1,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,FLUSH,5
"(♠A, ♠2, ♠3, ♠4, ♠8)",0,1,1,1,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,FLUSH,5
"(♠A, ♠2, ♠3, ♠4, ♠9)",0,1,1,1,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,FLUSH,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"(♦8, ♦9, ♦10, ♦J, ♦K)",0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,0,1,1,0,FLUSH,5
"(♦8, ♦9, ♦10, ♦Q, ♦K)",0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,1,1,FLUSH,5
"(♦8, ♦9, ♦J, ♦Q, ♦K)",0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,0,1,1,1,FLUSH,5
"(♦8, ♦10, ♦J, ♦Q, ♦K)",0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,1,1,1,FLUSH,5
"(♦9, ♦10, ♦J, ♦Q, ♦K)",0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,1,1,1,STRAIGHT FLUSH,8

# Building Models

In [8]:
from sklearn.linear_model import LogisticRegression, Perceptron
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

#### 1. Splitting to X and y

In [9]:
X = df.drop(['ranking', 'labels'], axis=1).to_numpy()
y = df['labels'].to_numpy()

In [15]:
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.metrics import accuracy_score

#### Splitting to TRAIN and TEST

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [12]:
models = [
#     {"model": LogisticRegression(random_state=1, n_jobs=-1),
#      "name": 'Logistic Regression',
#     "param_grid": {
#         "C": [0.001, 0.01, 0.1, 1, 10, 100, 1000],
#         "solver": ['liblinear', 'saga', 'newton-cg', 'lbfgs', 'sag'],
#         "penalty": ['l1', 'l2', 'elasticnet', 'none']
#         }
#     }
#     ,
#     {"model": Perceptron(random_state=1, n_jobs=-1),
#      "name": 'Perceptron',
#     "param_grid": {
#         "penalty": ['l2', 'l1', 'elastic'],
#         "alpha": [0.0001, 0.001, 0.01, 0.1, 1, 10, 100],
#         'tol' : [0.0001, 0.001, 0.01, 0.1, 1, 10, 100]
#         }
#     }
#     ,
#     {"model": DecisionTreeClassifier(random_state=1),
#      "name": 'DTC',
#     "param_grid": {
#         "criterion": ['gini', 'entropy', 'log_loss'],
#         "splitter": ['best', 'random'],
#         "min_samples_split" : list(range(2, 10))
#         }
#     }
#     ,
    {"model": RandomForestClassifier(random_state=1, n_jobs=-1),
     "name": 'RFC',
    "param_grid": {
        'criterion': ['gini', 'entropy', 'log_loss'],
        'min_samples_leaf': list(range(1, 11)),
        'n_estimators': list(range(100, 1001, 100)),
        'max_depth': list(range(1, 21)), 
        'max_features': list(range(1, 21))
        }
    }
]

In [16]:
base_result = []
for model in models:
    m = model['model']
    print(model['name'])
    %time m.fit(X_train, y_train)
    current_prediction = m.predict(X_test)
    score = accuracy_score(y_test, current_prediction)
    base_result.append({"name": model['name'], 
                       'estimator': m,
                       'score': score})

RFC
CPU times: total: 24min 56s
Wall time: 3min 55s

In [17]:
base_result

[{'name': 'RFC',
  'estimator': RandomForestClassifier(n_jobs=-1, random_state=1),
  'score': 0.9454576702475862}]

In [ ]:
result = []
for model in models:
    rand_search = RandomizedSearchCV(model['model'], model['param_grid'], cv=5, n_iter=10, n_jobs=-1)
    %time rand_search.fit(X, y)
    result.append({"name": model['name'], 
                   'estimator': rand_search.best_estimator_,
                   'score': rand_search.best_score_})

In [ ]:
result